##############################
# Netlify configuration file #
##############################

# List of Build plugins

[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "14.14.0"